let name = "Ankit Kumar";
let school = "Masai Public School";
let grade = 10;
let section = "B";
let rollno = 11221122;
let math_score = 72;
let english_score = 70;
let science_score = 80;
console.log("-----------------------------------------");
console.log("               Report Card               ");
console.log("-----------------------------------------");
console.log("Name:               | " + name);
console.log("Roll Number:        | " + rollno);
console.log("School:             | " + school);
console.log("Grade:              | " + grade + " " + section);
console.log("-----------------------------------------");
console.log("Mathematics:        | " + math_score);
console.log("English:            | " + english_score);
console.log("Science:            | " + science_score);
console.log("-----------------------------------------");
console.log("*******            PASS           *******");
console.log("-----------------------------------------");